<HomeScreen>:
    ContainerHost:
        BoxLayout:
            id: home__header
            orientation: "vertical"
            size_hint_y: None
            height: self.minimum_height

        BoxLayout:
            id: home__main
            orientation: "vertical"
            size_hint_y: 1

        BoxLayout:
            id: home__footer
            orientation: "vertical"
            size_hint_y: None
            height: self.minimum_height
