<HomeScreen>:
    ContainerHost:
        BoxLayout:
            id: home_header
            orientation: "vertical"
            size_hint_y: None
            height: self.minimum_height

        BoxLayout:
            id: home_main
            orientation: "vertical"
            size_hint_y: 1

        BoxLayout:
            id: home_footer
            orientation: "vertical"
            size_hint_y: None
            height: self.minimum_height
